# Updated wrangler.toml — single TASKLOGS_KV added for HjTaskman logs.
name = "gjtaskman"
compatibility_date = "2025-04-19"

main = "index.js"   # 推荐入口 index.js（需导出 GjTaskman 和 HjTaskman）
workers_dev = false

# Durable Object bindings
[[durable_objects.bindings]]
name = "GJTASKMAN"
class_name = "GjTaskman"

[[durable_objects.bindings]]
name = "HJTASKMAN"
class_name = "HjTaskman"

[vars]
# EXAMPLE_VAR = "some_value"

# D1 database binding (unchanged)
[[d1_databases]]
binding = "DB"
database_name = "vdown"
database_id = "03d64d46-1842-4403-846a-95fd01de87a7"

# Existing KV bindings (unchanged)
[[kv_namespaces]]
binding = "VINFOKV"
id = "80ef0424caac4d629ea752b810f5f8de"

[[kv_namespaces]]
binding = "USERVIDEO_KV"
id = "f20b7670a4a1475993f7c921c0521c83"

# NEW: single TASKLOGS_KV for hjtaskman raw log persistence
# Replace the id below with your KV namespace ID for task logs
[[kv_namespaces]]
binding = "TASKLOGS_KV"
id = "9485b8baeec8421f9bd99d184d42b7e1"

[[migrations]]
tag = "v1"
new_classes = [ "GjTaskman", "HjTaskman" ]
